In [15]:
import pandas as pd
import os

In [16]:
# Init dim and fact files directory
dim_courier_status_dir = '../dim_courier_status.csv'
dim_customer_dir = '../dim_customer.csv'
dim_date_dir = '../dim_date.csv'
dim_fulfillment_dir = '../dim_fulfillment.csv'
dim_product_dir = '../dim_product.csv'
dim_promotion_dir = '../dim_promotion.csv'
dim_status_dir = '../dim_status.csv'
fact_dir = '../fact_sales.csv'

In [17]:
# Read fact sales file and its corresponding dim tables(files)
df_dim_courier_status = pd.read_csv(dim_courier_status_dir)
df_dim_customer = pd.read_csv(dim_customer_dir)
df_dim_date = pd.read_csv(dim_date_dir)
df_dim_fulfillment = pd.read_csv(dim_fulfillment_dir)
df_dim_product = pd.read_csv(dim_product_dir)
df_dim_promotion = pd.read_csv(dim_promotion_dir)
df_dim_status = pd.read_csv(dim_status_dir)
df_fact_sales = pd.read_csv(fact_dir)

### Creating embedded fact_sales to upload in mongoDB

In [18]:
# Merge/join dimension(s) in fact_sales
df_embedded = df_fact_sales \
    .merge(df_dim_date, on="date_id", how="left") \
    .merge(df_dim_customer, on="customer_id", how="left") \
    .merge(df_dim_product, on="product_id", how="left") \
    .merge(df_dim_fulfillment, on="fulfillment_id", how="left") \
    .merge(df_dim_promotion, on="promotion_id", how="left") \
    .merge(df_dim_status, on="status_id", how="left") \
    .merge(df_dim_courier_status, on="courier_status_id", how="left")

df_embedded

,order_id,date_id,customer_id,product_id,fulfillment_id,promotion_id,status_id,courier_status_id,quantity,amount,...,SKU,Category,Style,Size,Fulfilment,Sales_Channel_,ship-service-level,promotion-ids,status_name,courier_status_name
0,405-8078784-5731545,1,1,1,1,1,1,1,0,647.62,...,SET389-KR-NP-S,Set,SET389,S,Merchant,Amazon.in,Standard,no promotion,Cancelled,unknown
1,171-9198151-1101146,1,2,2,1,2,2,2,1,406.00,...,JNE3781-KR-XXXL,kurta,JNE3781,3XL,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped
2,403-9615377-8133951,1,4,4,1,1,1,1,0,753.33,...,J0341-DR-L,Western Dress,J0341,L,Merchant,Amazon.in,Standard,no promotion,Cancelled,unknown
3,406-7807733-3785945,1,8,8,1,4,2,2,1,399.00,...,JNE3405-KR-S,kurta,JNE3405,S,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped
4,405-5513694-8146768,1,12,13,1,5,2,2,1,399.00,...,JNE3405-KR-XS,kurta,JNE3405,XS,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37523,405-4724097-1016369,91,16442,140,1,5769,2,2,1,854.00,...,J0009-SKD-S,Set,J0009,S,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped
37524,403-9524128-9243508,91,7510,2205,1,1,1,1,0,734.29,...,JNE3797-KR-XL,Western Dress,JNE3797,XL,Merchant,Amazon.in,Standard,no promotion,Cancelled,unknown
37525,405-6493630-8542756,32,183,201,1,5785,2,2,1,518.00,...,J0301-TP-M,Top,J0301,M,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped
37526,407-0116398-1810752,32,570,3004,1,1,1,1,0,398.10,...,BL019-71PINK-B,Blouse,BL019,Free,Merchant,Amazon.in,Standard,no promotion,Cancelled,unknown
37527,403-0317423-9322704,32,3056,2571,1,5704,2,2,1,721.00,...,JNE3869-DR-M,Western Dress,JNE3869,M,Merchant,Amazon.in,Standard,Amazon PLCC Free-Financing Universal Merchant ...,Shipped - Delivered to Buyer,Shipped

In [19]:
# Load embedded fact sales to csv file
data_dir = '../../Data'
df_embedded.to_csv(os.path.join(data_dir, 'fact_sales_embedded.csv'), index=False)

In [36]:
df_fact_sales['order_id'].duplicated().sum()

2811

In [35]:
duplicated_rows1 = df_fact_sales[df_fact_sales.duplicated(subset='order_id', keep=False)]

# Print the rows with duplicated order_id
duplicated_rows1

,order_id,date_id,customer_id,product_id,fulfillment_id,promotion_id,status_id,courier_status_id,quantity,amount,currency,B2B,fulfilled-by,timestamp
26,405-5257740-5301158,1,94,101,1,6,2,2,1,832.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
27,405-5257740-5301158,1,94,102,1,6,2,2,1,399.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
29,406-8961316-8137943,1,104,117,1,15,2,2,1,597.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
30,406-8961316-8137943,1,104,118,1,15,2,2,1,549.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
48,407-4936046-5852304,1,189,207,1,1,1,1,0,1249.11,INR,False,Easy Ship,2025-03-18 22:42:23.970145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37516,407-8043662-8470731,91,141,2386,1,5758,2,2,1,459.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
37517,407-8043662-8470731,91,141,1532,1,5758,2,2,1,487.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
37521,405-4724097-1016369,91,16442,3068,1,5769,2,2,1,999.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
37522,405-4724097-1016369,91,16442,2486,1,5769,2,2,1,1523.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145
37523,405-4724097-1016369,91,16442,140,1,5769,2,2,1,854.00,INR,False,Easy Ship,2025-03-18 22:42:23.970145

In [31]:
# Sales have 2811 duplicated orders, but in fact they are not duplicated
# The duplicated rows represent different products for each order
duplicated_rows = df_fact_sales[df_fact_sales.duplicated(subset=['order_id', 'product_id'], keep=False)]
len(duplicated_rows)

0